export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <header
        style={{
          backgroundColor:"navy",
          color: "white",
          padding: "1rem",
          textAlign: "center"
        }}
        >
      <p>HEADER</p>
      </header>

      {children}
      
      <footer
      style={{
        backgroundColor:"red",
        color:"white",
        padding:"1rem",
        textAlign:"center",
      }}>
        <p>FOOTER</p>
      </footer>
      </body>
    </html>
  )
}
